project:
  type: website
  title: "GISRUK 2025 Presentation"
  render:
    - index.qmd 
    - slides.qmd
    - paper.qmd
website:
  description: "Website with slides for my talk at GISRUK 2025"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: slides.qmd
      # - text: "Paper"
      #   href: paper.qmd
